name: Azure Functions CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
    paths: 
      - 'Orders.Backend/**'
      - 'Orders.Shared/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
    - master

env:
  AZURE_FUNCTIONAPP_NAME: 'ordersdemo'  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'published'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.201'              # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build Orders.Backend --configuration Release --output ./published
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
